<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRWBEp7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRWBEp7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCRWBEp7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCRWBEp7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCRWBEp7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CRWBEp7',
    'container.build_id' => '7f0432a2',
    'container.build_time' => 1534339427,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRWBEp7');
